name: Test1

on: # Event that triggers the workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: # A group of steps/jobs
  build:
    runs-on: ubuntu-latest # The type of machine to run the job on
    steps:
      - uses: actions/checkout@v4 # Correct syntax

      - name: one line script
        run: echo hello